# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7e11d97853611287e8f1196316389296"
name = "reeloo"
handle = "reeloo-5"
application_url = "https://swedish-rj-cst-district.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_files"

[auth]
redirect_urls = ["https://swedish-rj-cst-district.trycloudflare.com/auth/callback", "https://swedish-rj-cst-district.trycloudflare.com/auth/shopify/callback", "https://swedish-rj-cst-district.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
